spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:sqlserver://localhost:1433;databaseName=APD}
    username: sa
    password: 9076137aA$
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging.level: DEBUG
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
mail:
  server: api.mailgun.net
  apiKey: ${MAILGUN_API_KEY}
  domain: ${MAILGUN_DOMAIN}
  from: mail
twilio:
  account: ${TWILIO_ACCOUNT}
  key: ${TWILIO_KEY}
  from: ${TWILIO_FROM}